#!/bin/bash
#g++ -std=c++14 -lpthread -lboost_system t5.cpp -o server
#g++  -lpthread -lboost_thread -lboost_system t5.cpp -o server5
if [ $HOSTNAME == "raspberrypi" ]; then
  g++ -std=c++17 -lpthread  -lboost_system  -lboost_serialization /usr/lib/arm-linux-gnueabihf/libboost_system.so /usr/lib/arm-linux-gnueabihf/libboost_thread.so.1.67.0 SimpleServer.cpp -o servy
else
  g++ -c SimpleServer.cpp -std=c++17
  g++    SimpleServer.o   -o servy -lpthread  -lboost_system  -lboost_serialization 
fi
